#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

load_project_env() {
  [[ -f "$ROOT_DIR/.env" ]] || die ".env not found; run install.sh first"
  set -a
  # shellcheck source=../versions.env
  # shellcheck disable=SC1091
  source "$ROOT_DIR/versions.env"
  # .env is generated by this project with shell-safe values.
  # shellcheck source=/dev/null
  source "$ROOT_DIR/.env"
  set +a
}

compose() {
  docker compose \
    --env-file "$ROOT_DIR/versions.env" \
    --env-file "$ROOT_DIR/.env" \
    --project-directory "$ROOT_DIR" \
    -f "$ROOT_DIR/compose.yml" "$@"
}

random_hex() {
  local bytes=$1
  openssl rand -hex "$bytes"
}
